# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
