# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-14 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='media/default.png', upload_to='media/'),
        ),
    ]
